In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from pandas import read_csv
from sklearn.linear_model import LinearRegression

In [ ]:
from google.colab import files
data = files.upload()

Saving Shopping_center.csv to Shopping_center.csv


In [ ]:
df = pd.read_csv('Shopping_center.csv')

In [ ]:
df

Customer ID  Gender  Age  Annual Income in K$  Spending Points (1-100)
0          15101    Male   19                   15                       39
1          15102    Male   21                   15                       81
2          15103  Female   20                   16                        6
3          15104  Female   23                   16                       77
4          15105  Female   31                   17                       40
..           ...     ...  ...                  ...                      ...
195        15296  Female   35                  120                       79
196        15297  Female   45                  126                       28
197        15298    Male   32                  126                       74
198        15299    Male   32                  137                       18
199        15300    Male   30                  137                       83

[200 rows x 5 columns]

In [ ]:
df.shape

(200, 5)

In [ ]:
df.columns

Index(['Customer ID', 'Gender', 'Age', 'Annual Income in K$',
       'Spending Points (1-100)'],
      dtype='object')

In [ ]:
df.head()

Customer ID  Gender  Age  Annual Income in K$  Spending Points (1-100)
0        15101    Male   19                   15                       39
1        15102    Male   21                   15                       81
2        15103  Female   20                   16                        6
3        15104  Female   23                   16                       77
4        15105  Female   31                   17                       40

In [ ]:
df.tail()

Customer ID  Gender  Age  Annual Income in K$  Spending Points (1-100)
195        15296  Female   35                  120                       79
196        15297  Female   45                  126                       28
197        15298    Male   32                  126                       74
198        15299    Male   32                  137                       18
199        15300    Male   30                  137                       83

In [ ]:
df.describe()

Customer ID         Age  Annual Income in K$  Spending Points (1-100)
count    200.000000  200.000000           200.000000               200.000000
mean   15200.500000   38.850000            60.560000                50.200000
std       57.879185   13.969007            26.264721                25.823522
min    15101.000000   18.000000            15.000000                 1.000000
25%    15150.750000   28.750000            41.500000                34.750000
50%    15200.500000   36.000000            61.500000                50.000000
75%    15250.250000   49.000000            78.000000                73.000000
max    15300.000000   70.000000           137.000000                99.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Customer ID              200 non-null    int64 
 1   Gender                   200 non-null    object
 2   Age                      200 non-null    int64 
 3   Annual Income in K$      200 non-null    int64 
 4   Spending Points (1-100)  200 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 7.9+ KB


In [ ]:
df.isnull()

Customer ID  Gender    Age  Annual Income in K$  Spending Points (1-100)
0          False   False  False                False                    False
1          False   False  False                False                    False
2          False   False  False                False                    False
3          False   False  False                False                    False
4          False   False  False                False                    False
..           ...     ...    ...                  ...                      ...
195        False   False  False                False                    False
196        False   False  False                False                    False
197        False   False  False                False                    False
198        False   False  False                False                    False
199        False   False  False                False                    False

[200 rows x 5 columns]

In [ ]:
df.isnull().sum()

Customer ID                0
Gender                     0
Age                        0
Annual Income in K$        0
Spending Points (1-100)    0
dtype: int64

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['Gender'] = label_encoder.fit_transform(df['Gender'])
df['Gender'].unique()
df

Customer ID  Gender  Age  Annual Income in K$  Spending Points (1-100)
0          15101       1   19                   15                       39
1          15102       1   21                   15                       81
2          15103       0   20                   16                        6
3          15104       0   23                   16                       77
4          15105       0   31                   17                       40
..           ...     ...  ...                  ...                      ...
195        15296       0   35                  120                       79
196        15297       0   45                  126                       28
197        15298       1   32                  126                       74
198        15299       1   32                  137                       18
199        15300       1   30                  137                       83

[200 rows x 5 columns]

In [ ]:
df_array = df.values

In [ ]:
df_array

array([[15101,     1,    19,    15,    39],
       [15102,     1,    21,    15,    81],
       [15103,     0,    20,    16,     6],
       [15104,     0,    23,    16,    77],
       [15105,     0,    31,    17,    40],
       [15106,     0,    22,    17,    76],
       [15107,     0,    35,    18,     6],
       [15108,     0,    23,    18,    94],
       [15109,     1,    64,    19,     3],
       [15110,     0,    30,    19,    72],
       [15111,     1,    67,    19,    14],
       [15112,     0,    35,    19,    99],
       [15113,     0,    58,    20,    15],
       [15114,     0,    24,    20,    77],
       [15115,     1,    37,    20,    13],
       [15116,     1,    22,    20,    79],
       [15117,     0,    35,    21,    35],
       [15118,     1,    20,    21,    66],
       [15119,     1,    52,    23,    29],
       [15120,     0,    35,    23,    98],
       [15121,     1,    35,    24,    35],
       [15122,     1,    25,    24,    73],
       [15123,     0,    46,    

In [ ]:
x = df_array[:,0:4]

In [ ]:
x

array([[15101,     1,    19,    15],
       [15102,     1,    21,    15],
       [15103,     0,    20,    16],
       [15104,     0,    23,    16],
       [15105,     0,    31,    17],
       [15106,     0,    22,    17],
       [15107,     0,    35,    18],
       [15108,     0,    23,    18],
       [15109,     1,    64,    19],
       [15110,     0,    30,    19],
       [15111,     1,    67,    19],
       [15112,     0,    35,    19],
       [15113,     0,    58,    20],
       [15114,     0,    24,    20],
       [15115,     1,    37,    20],
       [15116,     1,    22,    20],
       [15117,     0,    35,    21],
       [15118,     1,    20,    21],
       [15119,     1,    52,    23],
       [15120,     0,    35,    23],
       [15121,     1,    35,    24],
       [15122,     1,    25,    24],
       [15123,     0,    46,    25],
       [15124,     1,    31,    25],
       [15125,     0,    54,    28],
       [15126,     1,    29,    28],
       [15127,     0,    45,    28],
 

In [ ]:
y = df_array[:,-1]

In [ ]:
y

array([39, 81,  6, 77, 40, 76,  6, 94,  3, 72, 14, 99, 15, 77, 13, 79, 35,
       66, 29, 98, 35, 73,  5, 73, 14, 82, 32, 61, 31, 87,  4, 73,  4, 92,
       14, 81, 17, 73, 26, 75, 35, 92, 36, 61, 28, 65, 55, 47, 42, 42, 52,
       60, 54, 60, 45, 41, 50, 46, 51, 46, 56, 55, 52, 59, 51, 59, 50, 48,
       59, 47, 55, 42, 49, 56, 47, 54, 53, 48, 52, 42, 51, 55, 41, 44, 57,
       46, 58, 55, 60, 46, 55, 41, 49, 40, 42, 52, 47, 50, 42, 49, 41, 48,
       59, 55, 56, 42, 50, 46, 43, 48, 52, 54, 42, 46, 48, 50, 43, 59, 43,
       57, 56, 40, 58, 91, 29, 77, 35, 95, 11, 75,  9, 75, 34, 71,  5, 88,
        7, 73, 10, 72,  5, 93, 40, 87, 12, 97, 36, 74, 22, 90, 17, 88, 20,
       76, 16, 89,  1, 78,  1, 73, 35, 83,  5, 93, 26, 75, 20, 95, 27, 63,
       13, 75, 10, 92, 13, 86, 15, 69, 14, 90, 32, 86, 15, 88, 39, 97, 24,
       68, 17, 85, 23, 69,  8, 91, 16, 79, 28, 74, 18, 83])

# **Standarization**

**Min Max Scaler**

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler = MinMaxScaler()
scaler = scaler.fit_transform(df)

In [ ]:
scaler

array([[0.        , 1.        , 0.01923077, 0.        , 0.3877551 ],
       [0.00502513, 1.        , 0.05769231, 0.        , 0.81632653],
       [0.01005025, 0.        , 0.03846154, 0.00819672, 0.05102041],
       [0.01507538, 0.        , 0.09615385, 0.00819672, 0.7755102 ],
       [0.0201005 , 0.        , 0.25      , 0.01639344, 0.39795918],
       [0.02512563, 0.        , 0.07692308, 0.01639344, 0.76530612],
       [0.03015075, 0.        , 0.32692308, 0.02459016, 0.05102041],
       [0.03517588, 0.        , 0.09615385, 0.02459016, 0.94897959],
       [0.04020101, 1.        , 0.88461538, 0.03278689, 0.02040816],
       [0.04522613, 0.        , 0.23076923, 0.03278689, 0.7244898 ],
       [0.05025126, 1.        , 0.94230769, 0.03278689, 0.13265306],
       [0.05527638, 0.        , 0.32692308, 0.03278689, 1.        ],
       [0.06030151, 0.        , 0.76923077, 0.04098361, 0.14285714],
       [0.06532663, 0.        , 0.11538462, 0.04098361, 0.7755102 ],
       [0.07035176, 1.        , 0.

**Z score and standard scaler(same)**

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x)

StandardScaler()

In [ ]:
x_scaled = scaler.transform(x)

In [ ]:
x_scaled

array([[-1.7234121 ,  1.12815215, -1.42456879, -1.73899919],
       [-1.70609137,  1.12815215, -1.28103541, -1.73899919],
       [-1.68877065, -0.88640526, -1.3528021 , -1.70082976],
       [-1.67144992, -0.88640526, -1.13750203, -1.70082976],
       [-1.6541292 , -0.88640526, -0.56336851, -1.66266033],
       [-1.63680847, -0.88640526, -1.20926872, -1.66266033],
       [-1.61948775, -0.88640526, -0.27630176, -1.62449091],
       [-1.60216702, -0.88640526, -1.13750203, -1.62449091],
       [-1.5848463 ,  1.12815215,  1.80493225, -1.58632148],
       [-1.56752558, -0.88640526, -0.6351352 , -1.58632148],
       [-1.55020485,  1.12815215,  2.02023231, -1.58632148],
       [-1.53288413, -0.88640526, -0.27630176, -1.58632148],
       [-1.5155634 , -0.88640526,  1.37433211, -1.54815205],
       [-1.49824268, -0.88640526, -1.06573534, -1.54815205],
       [-1.48092195,  1.12815215, -0.13276838, -1.54815205],
       [-1.46360123,  1.12815215, -1.20926872, -1.54815205],
       [-1.4462805 , -0.

Regression with scaled features

In [ ]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression()

In [ ]:
reg.coef_ #coefficient

array([-0.29947691, -0.99839047, -8.37003934,  0.5003864 ])

In [ ]:
reg.intercept_  #intercept

50.2

Creating a Summary Table

In [ ]:
reg_summary = pd.DataFrame([['Bias'],['x'],['y']], columns=['Features'])

In [ ]:
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [ ]:
reg_summary

Features    Weights
0     Bias  50.200000
1        x  -0.299477
2        y  -0.998390